# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
    networks:
      - escape_net
  web:
    image: php:7.2.2-apache
    build: ./
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./../:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    networks:
      - escape_net

networks:
  escape_net: