# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
    networks:
      - escape_net

  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ../dbscripts:/flyway/sql
      - ../dbscripts:/flyway/conf
    networks:
      - escape_net
    depends_on:
      - db

  web:
    image: php:7.4.6-apache
    build: ./
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./../:/var/www/html/
    ports:
      - "8100:80"
    networks:
      - escape_net

networks:
  escape_net: