# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
    networks:
      - escape_net
    volumes:
      - ./mysql_data:/var/lib/mysql
# TODO test dbvolumes...

  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ../dbscripts:/flyway/sql
      - ../dbscripts:/flyway/conf
    networks:
      - escape_net
    depends_on:
      - db

  react:
    image: blog-react:alpine3.16
    build:
      context: ./
      dockerfile: Dockerfile-react
    container_name: react_build
    ports:
      - "3000:3000"
    volumes:
      - ../react:/my-blog-app
    networks:
      - escape_net

  web:
    image: blog-phpserv:7.4.6-apache
    build:
      context: ./
      dockerfile: Dockerfile-php
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./../:/var/www/html/
    ports:
      - "8100:80"
    networks:
      - escape_net

networks:
  escape_net: