# ./docker-compose.yml

version: '3'

services:
  blog-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    command: --explicit_defaults_for_timestamp=true
    ports:
      - "9906:3306"
    volumes:
      - blog_sqlData:/var/lib/mysql

  blog-flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ../dbscripts:/flyway/sql
      - ../dbscripts:/flyway/conf
    depends_on:
      - blog-db

  blog-web:
    image: blog-phpserv:7.4.6-apache
    build:
      context: ./
      dockerfile: Dockerfile-php
    depends_on:
      - blog-db
    volumes:
      - ./../env:/var/www/html/
    ports:
      - "8100:80"

  blog-api:
    image: blog-phpserv:7.4.6-apache
    build:
      context: ./
      dockerfile: Dockerfile-php
    depends_on:
      - blog-db
    volumes:
      - ./../api/src:/var/www/html/
      - ./../api/test:/phptest/test
    ports:
      - "8200:80"

  blog-js:
    image: blog-phpserv:7.4.6-apache
    build:
      context: ./
      dockerfile: Dockerfile-php
    depends_on:
      - blog-api
    volumes:
      - ./../playground:/var/www/html/
    ports:
      - "8300:80"

volumes:
  blog_sqlData: