CREATE TABLE `ARTICLES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(500) NOT NULL,
  `CREATED` date NOT NULL,
  `CONTENT` varchar(20000) NOT NULL,
  `ACTIVE` int(11) NOT NULL DEFAULT '1',

  PRIMARY KEY (`ID`)
);

CREATE TABLE `CATEGORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(500) NOT NULL,

  PRIMARY KEY (`ID`)
);

CREATE TABLE `ART_CAT` (
  `ARTICLE` int(11) NOT NULL,
  `CATEGORY` int(11) NOT NULL
);

CREATE TABLE `LOGINREGISTER` (
  `ATTEMPT` int(11) NOT NULL
);
